version: 2.1
jobs:
  miracle-build:
    #  machine: true
    #  resource_class: eridanhq/demo-test1
     machine:
      image: ubuntu-2004:2022.10.1
     steps:
       - checkout
       - run:
           name: "Build Miraclelib"
           command: make all
       - run:
           name: "Build Split E C plane"
           command: cd ui/split8 && make client && make server
           no_output_timeout: 120m

       - run:
           name: "Unit tests:"
           command: cd ui/split8 && make tests
           no_output_timeout: 120m

workflows:
   miracle-workflow:
       jobs:
          - miracle-build
